apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stable-diffusion
  name: stable-diffusion-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 30
  selector:
    matchLabels:
      app: stable-diffusion
  template:
    metadata:
      labels:
        app: stable-diffusion
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4
        # cloud.google.com/gke-spot: "true"
      containers:
      - image: asia-northeast1-docker.pkg.dev/empowerme-bb3c5/empowerme-diffusion/f15ea9c:latest
        name: stable-diffusion
        resources:
          limits:
            nvidia.com/gpu: "1"
          requests:
            cpu: "8"
            memory: "8Gi"
